name: Continuous Integration

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      - name: test
        run: cd go && make test
